// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lckgrgfhfvxplhzbsaka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxja2dyZ2ZoZnZ4cGxoemJzYWthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NTM3MDMsImV4cCI6MjA4ODIyOTcwM30.2EiAceNRPXpZIDG8vs8ijY_R5KmloBcs9U8hMa4uGww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
